#!/bin/sh
set -e

dst="/var/www/htdocs/$(basename "$(pwd)" '.git')"
src="$dst/raw"

rm -f "$dst/.files"
rm -rf "$src"
git clone . "$src"

"/var/www/src/bin/ssg3" "$src" "$dst" 'RUN BSD' 'https://runbsd.info'

hostname > "$dst/hostname"
