#!/bin/sh -e

title='Run BSD'
url='https://runbsd.info/'

pwd=$(pwd)
if test -z "${pwd##*.git}"
then repo="$pwd"
else repo="$pwd/.git"
fi

dst="/var/www/htdocs/$(basename "$pwd" '.git')"
src="$dst/raw"

rm -rf "${dst:?}/.files"
rm -rf "${src:?}"
git clone . "$src"

"$src/index" "$src/people.txt" > "$src/index.html"
>&2 echo "[index] $(wc -l < "$src/people.txt" | tr -d ' ') people"

"/var/www/src/bin/ssg4" "$src" "$dst" "$title" "$url" > /dev/null

mkdir -p "$dst/src"
echo "$title" > "$repo/owner"
echo "$url" > "$repo/description"
(cd "$dst/src" && stagit "$pwd")
cp -f "$dst/src/log.html" "$dst/src/index.html"
cp -f "$dst/stagit/"* "$dst/src/"
>&2 echo "[stagit] $(grep -c '"commit' "$dst/src/log.html") commits"

hostname > "$dst/hostname"
