#!/bin/sh -e

title='Run BSD'
url='https://runbsd.info'

if test -z "${PWD##*.git}"
then repo="$PWD"
else repo="$PWD/.git"
fi

dst="/var/www/htdocs/$(basename "$PWD" '.git')"
raw="$dst/raw"
src="$dst/src"

rm -rf "${dst:?}/.files"
rm -rf "${raw:?}"
rm -rf "${src:?}"
git clone "$repo" "$raw"
(cd "$raw/.git" && git update-server-info)

"/var/www/src/bin/ssg4" "$raw" "$dst" "$title" "$url" > /dev/null

mkdir -p "$src"
echo "${title}" > "$repo/owner"
echo "${url##*//}" > "$repo/description"
echo "${url}/raw/.git" > "$repo/url"
(cd "$src" && stagit "$repo")
cp -f "$src/log.html" "$src/index.html"
cp -f "$dst/stagit/"* "$src/"
>&2 echo "[stagit] $(grep -c '"commit' "$src/log.html") commits"

hostname > "$dst/hostname"
